### ISSUE TITLE
GEdit plugin can find wrong example dir ?

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#105]
Created new virtualenv using

```
mkvirtualenv shoebot-pip
pip install shoebot
```

Chose venv in gedit plugin, but ended up with file from /usr/local from another install :/

**Comment by stuaxo** [comment]
Clue in gedit startup:

```
$ gedit
Could not find shoebot examples at /mnt/data/home/stu/.virtualenvs/shoebot-pip/lib/python2.7/site-packages/examples/
Traceback (most recent call last):
  File "/home/stu/.local/share/gedit/plugins/shoebotit/__init__.py", line 310, in do_activate
    base, menu = mk_menu(_("Shoebot"))
  File "/home/stu/.local/share/gedit/plugins/shoebotit/__init__.py", line 296, in mk_menu
    examples_item, examples = gtk3_utils.mk_examples_menu(_("E_xamples"))
ValueError: too many values to unpack (expected 2)
```

**Comment by stuaxo** [comment]
should be ```.virtualenvs/shoebot-pip/share/shoebot/examples```

**Comment by stuaxo** [comment]
Possibly had old shoebot plugin installed :)

- Seems like NOTABUG
