### ISSUE TITLE
some cairo bug ( cairo.RecordingSurface)

### ISSUE THREAD

**Issue by AnnaMag** [shoebot/shoebot#116]
Running
https://gist.github.com/AnnaMag/7cf4d66bbe5b97e519eb90ef591437de

gives an error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/grammar.py", line 284, in run
    self._run_frame(executor, limit=frame_limiter, iteration=iteration)
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/grammar.py", line 148, in _run_frame
    executor.run()
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/livecode.py", line 116, in run
    self.do_exec(self.known_good, self.ns)
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/livecode.py", line 83, in do_exec
    exec source in ns
  File "<string>", line 28, in <module>
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/data/bezier.py", line 199, in contains
    record_surface = cairo.RecordingSurface(cairo.CONTENT_COLOR_ALPHA, 0, 0)
TypeError: __init__() takes exactly 3 arguments (4 given)

**Comment by stuaxo** [comment]
Whats the command you use to run shoebot with (so I can see which backend it's using) ?

**Comment by AnnaMag** [comment]
simply
sbot fill_text.py

**Comment by stuaxo** [comment]
Fixed - good catch - missed this in port to Gtk3.

Probably the same bug in other places, will fix.

This is awesome, it's the most it's worked on a mac for a while :)

**Comment by AnnaMag** [comment]
great!
