### ISSUE TITLE
pdf oututput dies

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#117]
This looks like a typo might have crept in 

```
Error in the Shoebot script at line 81  in create_rcontext
    surface = cairo.PDFSurface(self._output_vfile(frame)  *size):
77:         """
78:         Called when CairoCanvas needs a cairo context to draw on
79:         """
80:         if self.format == 'pdf':
81:             surface = cairo.PDFSurface(self._output_vfile(frame), *size)
    ^ AttributeError: 'CairoImageSink' object has no attribute '_output_vfile'

Traceback (most recent call last):
  File "/mnt/data/home/stu/projects/mine/shoebot/shoebot/core/canvas.py", line 169, in flush
    self.sink.render(self.size_or_default(), frame, self._drawqueue)
  File "/mnt/data/home/stu/projects/mine/shoebot/shoebot/core/drawqueue_sink.py", line 21, in render
    r_context = self.create_rcontext(size, frame)
  File "/mnt/data/home/stu/projects/mine/shoebot/shoebot/core/cairo_sink.py", line 81, in create_rcontext
    surface = cairo.PDFSurface(self._output_vfile(frame), *size)
AttributeError: 'CairoImageSink' object has no attribute '_output_vfile'
```

**Comment by stuaxo** [comment]
Fixed
