### ISSUE TITLE
traceback is not correct

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#120]
This should show line 95 - probably should show where it was triggered too ?

```
Error in the Shoebot script at line 116  in run
    self.do_exec(self.known_good  self.ns):
95: colors.gradientfill(
96:     rect(0, 0, WIDTH, HEIGHT, draw=False),
97:     bg.darken(0.25),
98:     bg.lighten(0.25),
99:     spread=0.75
    ^ NotImplementedError: gradientpath not implemented yet.

```

Native version

```
Traceback (most recent call last):
  File "/mnt/data/home/stu/projects/mine/shoebot/shoebot/grammar/grammar.py", line 284, in run
    self._run_frame(executor, limit=frame_limiter, iteration=iteration)
  File "/mnt/data/home/stu/projects/mine/shoebot/shoebot/grammar/grammar.py", line 148, in _run_frame
    executor.run()
  File "/mnt/data/home/stu/projects/mine/shoebot/shoebot/grammar/livecode.py", line 116, in run
    self.do_exec(self.known_good, self.ns)
  File "/mnt/data/home/stu/projects/mine/shoebot/shoebot/grammar/livecode.py", line 83, in do_exec
    exec source in ns
  File "<string>", line 99, in <module>
  File "/mnt/data/home/stu/projects/mine/shoebot/lib/colors/__init__.py", line 3096, in __init__
    raise NotImplementedError("gradientpath not implemented yet.")
NotImplementedError: gradientpath not implemented yet.
```

**Comment by rlafuente** [comment]
Totally, this is an old rock in the shoe. I remember having left the traceback code in a minimal state out of frustration at the time -- hacked at it until it worked minimally then left it...

**Comment by stuaxo** [comment]
As you can see, I hacked it some more... but not to "working"  I guess we should work out what tracebacks should look like, and then do that.

On the plus side, if we DO get it working, we can now add a unittest for it, so it doesn't break.

**Comment by rlafuente** [comment]
Yeah, saw it shortly after I posted :p I'd say it's in a pretty usable state, but prettifying is always nice if we happen to find the right procrastination mindset!

**Comment by stuaxo** [comment]
Turns out it's not a bug ...

Inside colors.py there is

gradientfill = gradientpath
