### ISSUE TITLE
Investigate runnable for running shoebot onlin

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#127]
http://code.runnable.com/

Probably need at least rendering to cairo working.... though I have no clue.

**Comment by stuaxo** [comment]
Hrm, maybe I have misunderstood what runnable is for..

**Comment by rlafuente** [comment]
They seem to have been acquired and the service shut down...

Maybe [PythonAnywhere](https://www.pythonanywhere.com/) could work for this. But I'm not sure if that's what Runnable was used for.

**Comment by stuaxo** [comment]
I can't remember what runnable was either :)

Are there any examples of generating graphics on PythonAnywhere ?

I guess if we start with static bots it's easiest.

Jupyter notebooks are kind of related + can be run on mybinder.
I experimented with this https://github.com/fomightez/cairo-jupyter a while ago - before handing it over to the current dev.   
The idea was to eventually use it for to build a shoebot extension on.

**Comment by stuaxo** [comment]
Hosted:

Mybinder (Jupyter)
- would needs cairo-jupyter to work a bit better

PythonAnywhere
- if PyCairo and the other libraries work then we can probably run.
Not sure how we hook up editing 


Browser based

This must be the ultimate goal.  We would probably need a new graphics back-end.

Options for running python include brython and pypy llvm

**Comment by stuaxo** [comment]
Is our jupyter support in a good enough state to try this again?

**Comment by rlafuente** [comment]
From what I remember last time I touched it, it was running pretty well and I wrote some basic docs ([repo here](https://github.com/shoebot/jupyter-shoebot/)) -- maybe at this point it's worth installing from that branch and try it out.

And PythonAnywhere seems to support PyCairo out-of-the-box from their [installed package list](https://www.pythonanywhere.com/batteries_included/). Will try it out there.

**Comment by rlafuente** [comment]
Trying to install it on PythonAnywhere, it installs without issue with

```bash
pip2.7 install --user git+git://github.com/shoebot/shoebot
```

But running `sbot --help`, I get:

```
Traceback (most recent call last):
  File "/home/rlafuente/.local/bin/sbot", line 11, in <module>
    load_entry_point('shoebot==1.2.3', 'console_scripts', 'sbot')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", li
ne 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", li
ne 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", li
ne 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", li
ne 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/rlafuente/.local/lib/python2.7/site-packages/shoebot/__init__.p
y", line 36, in <module>
    from shoebot.core.backend import cairo
  File "/home/rlafuente/.local/lib/python2.7/site-packages/shoebot/core/__ini
t__.py", line 39, in <module>
    from cairo_canvas import CairoCanvas
  File "/home/rlafuente/.local/lib/python2.7/site-packages/shoebot/core/cairo
_canvas.py", line 35, in <module>
    from .backend import cairo
  File "/home/rlafuente/.local/lib/python2.7/site-packages/shoebot/core/backe
nd.py", line 142, in <module>
    driver = CairoGIBackend(get_driver_options())
  File "/home/rlafuente/.local/lib/python2.7/site-packages/shoebot/core/backe
nd.py", line 95, in __init__
    self.gi_lib, self.gi_module = self.setup_gi(gi_pref)
  File "/home/rlafuente/.local/lib/python2.7/site-packages/shoebot/core/backend.py", line 104, in setup_gi
    name, gi_module = self.import_libs(['gi', 'pgi'], 'gi')
  File "/home/rlafuente/.local/lib/python2.7/site-packages/shoebot/core/backend.py", line 63, in import_libs
    raise ImportError('No %s Implementation found, tried: %s' % (impl_name, ' '.join(module_names)))
ImportError: No gi Implementation found, tried: gi pgi
```

**Comment by stuaxo** [comment]
That error is saying it can't find pygobject (or pgi - which is a bad option anyway).

It probably is a bug that it dies like that, try installing pygobject first and it works.

```$ pip install pygobject --user```

... (then install shoebot again)

I think I temporarily took out pygobject because of an issue on travis.

I think - it needs to be added back in, but on travis we need to install the dependencies manually (using vext.gi instead of pygobject), then install shebot with  `pip --no-deps`
