### ISSUE TITLE
text() throwing NotImplementedError when shoebot used as module

### ISSUE THREAD

**Issue by respatialized** [shoebot/shoebot#128]
I installed shoebot via pip from the zipball to make it play nicely with the rest of my packages (I'm using Miniconda as my system Python). At first, it works for various drawing functions, but then when adding text, I get the following error code:

```
NotImplementedErrorTraceback (most recent call last)
<ipython-input-17-789ff3e915ee> in <module>()
     13 #    bot.oval(100,i*10,50,50)
     14 #
---> 15 bot.text("sample",300,300)
     16 bot.finish()

.../miniconda2/lib/python2.7/site-packages/shoebot/grammar/nodebox.pyc in text(self, txt, x, y, width, height, outline, draw, **kwargs)
    689         :return: Path object representing the text.
    690         '''
--> 691         txt = self.Text(txt, x, y, width, height, outline=outline, ctx=None, **kwargs)
    692         if outline:
    693           path = txt.path

.../miniconda2/lib/python2.7/site-packages/shoebot/grammar/bot.pyc in Text(self, *args, **kwargs)
    245         return self._makeColorableInstance(Image, args, kwargs)
    246     def Text(self, *args, **kwargs):
--> 247         return self._makeColorableInstance(Text, args, kwargs)
    248 
    249     #### Variables

.../miniconda2/lib/python2.7/site-packages/shoebot/grammar/bot.pyc in _makeColorableInstance(self, clazz, args, kwargs)
    224 
    225         kwargs['strokewidth'] = kwargs.get('strokewidth', self._canvas.strokewidth)
--> 226         inst = clazz(self, *args, **kwargs)
    227         return inst
    228 

.../miniconda2/lib/python2.7/site-packages/shoebot/data/typography.pyc in __init__(self, bot, text, x, y, width, height, outline, ctx, enableRendering, **kwargs)
    109 
    110         #we need to pre-render some stuff to enable metrics sizing
--> 111         self._pre_render()
    112 
    113         if self._doRender: #this way we do not render if we only need to create metrics

.../miniconda2/lib/python2.7/site-packages/shoebot/data/typography.pyc in _pre_render(self)
    126         if GI:
    127             cr = _UNSAFE_cairocffi_context_to_pycairo(cr)
--> 128         self._pang_ctx = PangoCairo.create_context(cr)
    129         self.layout = PangoCairo.create_layout(cr)
    130         # layout line spacing

.../miniconda2/lib/python2.7/site-packages/pgi/module.pyc in __getattr__(self, name)
     86         cls = _attr_list[info.type.value]
     87         if cls:
---> 88             attr = cls(info)
     89             setattr(self, name, attr)
     90         else:

.../miniconda2/lib/python2.7/site-packages/pgi/function.pyc in FunctionAttribute(info)
     10 
     11 def FunctionAttribute(info):
---> 12     return generate_function(info)

.../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.pyc in generate_function(info, method)
    309         return func
    310 
--> 311     raise NotImplementedError("\n".join(messages))
    312 
    313 

NotImplementedError: cffi: Traceback (most recent call last):
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.py", line 302, in generate_function
    return_type, method)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.py", line 184, in _generate_function
    block = arg.pre_call()
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/arguments.py", line 357, in pre_call
    var = self.get_type()
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/arguments.py", line 109, in get_type
    self.type, desc=self.desc, may_be_null=self.may_be_null)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/cffi_backend.py", line 404, in get_type
    return get_type(type_, self._gen, desc, may_be_null, may_return_null)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/cffi_backend.py", line 95, in get_type
    raise NotImplementedError(e)
NotImplementedError: ('type: %r', 'INTERFACE')

ctypes: Traceback (most recent call last):
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.py", line 302, in generate_function
    return_type, method)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.py", line 197, in _generate_function
    throws)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/ctypes_backend/main.py", line 107, in get_function
    "Library doesn't provide symbol: %s" % symbol)
NotImplementedError: Library doesn't provide symbol: pango_cairo_create_context
```

Here's the minimal code to reproduce the bug:
```Python
import shoebot
bot = shoebot.create_bot(outputfile='output.svg')
bot.size(400,400)
bot.text('sample',300,300)
```

Should I assume this is an error with the way I've chosen to install shoebot? Or is there a different underlying issue here?

**Comment by stuaxo** [comment]
It looks like you have pgi installed and Shoebot is using this binding instead of the default GLib bindings.

Paste the output of the ```python setup.py diagnose``` to confirm this.


Shoebot works best using the default GLib bindings, but it can use pgi when these aren't available.

PGI is not yet complete - PangoCairo which Shoebot uses to render text is not available.

https://github.com/pygobject/pgi/issues/13


If you can use the default GLIb bindings in Miniconda then everything should "just work".  It's definitely possible in ordinary python on windows at least.

If it works then it would be great to add Miniconda instructions to the docs.

**Comment by respatialized** [comment]
Looks like it - no setup.py file is included in the miniconda directory, but `$ python diagnose.py` is pointing in the direction you're talking about:

```
miniconda2/lib/python2.7/site-packages/shoebot $ python diagnose.py
sys.executable:  .../miniconda2/bin/python
virtualenv: no
Python version: ['2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) ', '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]']
    dist: ('debian', 'stretch/sid', '')
    linux_distribution: ('debian', 'stretch/sid', '')
    system: Linux
    machine: x86_64
    platform: Linux-4.4.0-53-generic-x86_64-with-debian-stretch-sid
    version: #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
    mac_ver: ('', ('', '', ''), '')
    win32_ver: ('', '', '', '')
    
import gi                   [failed]
Pango won't be available
import pgi                  [success] : .../miniconda2/lib/python2.7/site-packages/pgi/__init__.pyc
import vext                 [success] : .../miniconda2/lib/python2.7/site-packages/vext/__init__.pyc
import pubsub               [success] : .../miniconda2/lib/python2.7/site-packages/pubsub.pyc
import meta                 [success] : .../miniconda2/lib/python2.7/site-packages/meta/__init__.pyc
import shoebot              [success] : .../miniconda2/lib/python2.7/site-packages/shoebot/__init__.pyc
shoebot - standard module example:
[passed] : /tmp/shoebot-standard_module_example.png
shoebot - module using text:
Traceback (most recent call last):
  File "diagnose.py", line 100, in run
    f(bot)
  File "diagnose.py", line 120, in module_using_text
    bot.text("Should work with gi not pgi", 0, 0)
  File ".../miniconda2/lib/python2.7/site-packages/shoebot/grammar/nodebox.py", line 691, in text
    txt = self.Text(txt, x, y, width, height, outline=outline, ctx=None, **kwargs)
  File ".../miniconda2/lib/python2.7/site-packages/shoebot/grammar/bot.py", line 247, in Text
    return self._makeColorableInstance(Text, args, kwargs)
  File ".../miniconda2/lib/python2.7/site-packages/shoebot/grammar/bot.py", line 226, in _makeColorableInstance
    inst = clazz(self, *args, **kwargs)
  File ".../miniconda2/lib/python2.7/site-packages/shoebot/data/typography.py", line 111, in __init__
    self._pre_render()
  File ".../miniconda2/lib/python2.7/site-packages/shoebot/data/typography.py", line 128, in _pre_render
    self._pang_ctx = PangoCairo.create_context(cr)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/module.py", line 88, in __getattr__
    attr = cls(info)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/function.py", line 12, in FunctionAttribute
    return generate_function(info)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.py", line 311, in generate_function
    raise NotImplementedError("\n".join(messages))
NotImplementedError: cffi: Traceback (most recent call last):
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.py", line 302, in generate_function
    return_type, method)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.py", line 184, in _generate_function
    block = arg.pre_call()
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/arguments.py", line 357, in pre_call
    var = self.get_type()
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/arguments.py", line 109, in get_type
    self.type, desc=self.desc, may_be_null=self.may_be_null)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/cffi_backend.py", line 404, in get_type
    return get_type(type_, self._gen, desc, may_be_null, may_return_null)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/cffi_backend.py", line 95, in get_type
    raise NotImplementedError(e)
NotImplementedError: ('type: %r', 'INTERFACE')

ctypes: Traceback (most recent call last):
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.py", line 302, in generate_function
    return_type, method)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/funcgen.py", line 197, in _generate_function
    throws)
  File ".../miniconda2/lib/python2.7/site-packages/pgi/codegen/ctypes_backend/main.py", line 107, in get_function
    "Library doesn't provide symbol: %s" % symbol)
NotImplementedError: Library doesn't provide symbol: pango_cairo_create_context

[failed]
```

Trying now to get GLib working. Will update as I make progress. Thanks!

**Comment by stuaxo** [comment]
If you can get pycairo installed then things will work (though without the GUI).

diagnose has been updated to have nicer output in the current version.

This could do with better error messaging.

**Comment by stuaxo** [comment]
I'm quite impressed pgi works with this, this looks like something I need to try.

**Comment by stuaxo** [comment]
Let me know how to get miniconda setup with the same libraries you are using and I can have a look into it.
