### ISSUE TITLE
fatpath example dies

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#154]
The fatpath example from here  https://www.nodebox.net/code/index.php/Fatpath

Dies because of differences in our path implementation:

```
path_op <shoebot.data.bezier.BezierPath object at 0x7ffba37fff10> <shoebot.data.bezier.BezierPath object at 0x7ffba37ffe50> <function pe_sub at 0x7ffba38e2c80>
path sop
path_op <shoebot.data.bezier.BezierPath object at 0x7ffba37ffe50> <shoebot.data.bezier.BezierPath object at 0x7ffba381b350> <function pe_add at 0x7ffba38e2c08>
Error in the Shoebot script at line 116  in run
    self.do_exec(self.known_good  self.ns):
252:     print
253:     print
254:     main()
255: 
256: main()
     ^ PathMathError: PathMathError Length of path 46 != 40

Traceback (most recent call last):
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/grammar/livecode.py", line 116, in run
    self.do_exec(self.known_good, self.ns)
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/grammar/livecode.py", line 83, in do_exec
    exec source in ns
  File "<string>", line 256, in <module>
  File "<string>", line 218, in main
  File "<string>", line 199, in fatpath
  File "<string>", line 162, in path_add
  File "<string>", line 159, in path_gop
  File "<string>", line 138, in path_op
  File "<string>", line 133, in path_assert_len
PathMathError: PathMathError Length of path 46 != 40
```

This should be added into tests/bots/bugs.

**Comment by stuaxo** [comment]
Nothing is likely to happen on this until https://github.com/shoebot/shoebot/issues/166 is implemented.
