### ISSUE TITLE
Add --verbose option and hide internal part of errors by default

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#18]
if I make an erronious script like

```python
rect(40, 40, 40)
```

I get an error that includes info internal to shoebot ... by default the user should just get the script error, unless they specify verbose on the commandline:

Example current output
```
Traceback (most recent call last):
  File "/home/stu/.virtualenvs/shoebot/bin/sbot", line 146, in <module>
    args = args.args)
  File "/home/stu/.virtualenvs/shoebot/local/lib/python2.7/site-packages/shoebot/sbot.py", line 86, in run
    bot.sb_run(src, iterations, run_forever = window if close_window == False else False, frame_limiter = window)
  File "/home/stu/.virtualenvs/shoebot/local/lib/python2.7/site-packages/shoebot/grammar/grammar.py", line 146, in sb_run
    self._exec_frame(source_or_code, limit = frame_limiter)
  File "/home/stu/.virtualenvs/shoebot/local/lib/python2.7/site-packages/shoebot/grammar/grammar.py", line 98, in _exec_frame
    exec source_or_code in namespace
  File "shoebot_code", line 1, in <module>
TypeError: rect() takes at least 5 arguments (4 given)
```

Desired output (without --verbose) might look something like this..
```
Traceback (most recent call last):
  File "shoebot_code", line 1, in <module>
TypeError: rect() takes at least 5 arguments (4 given)
```

**Comment by stuaxo** [comment]
About 2 years too late have integrated the change from this branch.
