### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by andrew-harrison** [shoebot/shoebot#198]
I'm struggling to install, it looks like there are some directories I'm missing. I've run the install dependencies script no problem but the setup.py fails to install.

I'm new to Python and still learning! I'm installing on Ubuntu.
Python Version:
Python 2.7.15rc1

andrew@andrew:~/shoebot-master$     python setup.py diagnose
running diagnose
Traceback (most recent call last):
  File "setup.py", line 201, in <module>
    test_suite='tests.unittests'
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 145, in setup
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 78, in run
    from shoebot.diagnose import diagnose
  File "/home/andrew/shoebot-master/shoebot/__init__.py", line 35, in <module>
    import cairocffi as cairo
ImportError: No module named cairocffi

andrew@andrew:~/shoebot-master$     python setup.py test
running test
Searching for planar
Reading https://pypi.org/simple/planar/
Downloading https://files.pythonhosted.org/packages/3f/1a/f19895d1a94461b438758135c2104d870bcff97dee085840a9b8f62dcc9c/planar-0.4.zip#sha256=cbfb9cbae8b0e296e6e7e3552b7d685c7ed5cae295b7a61f2b2b096b231dad76
Best match: planar 0.4
Processing planar-0.4.zip
Writing /tmp/easy_install-xbmizp/planar-0.4/setup.cfg
Running planar-0.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xbmizp/planar-0.4/egg-dist-tmp-8U0F9z
warning: no files found matching '*' under directory 'include'
warning: no files found matching '*' under directory 'examples'
no previously-included directories found matching '**/.hg'
no previously-included directories found matching 'doc/build/doctest'
no previously-included directories found matching 'doc/build/doctrees'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.out' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by stuaxo** [comment]
Hi,
   See if running this script helps;

./install/install_dependencies.sh


This functionality should probably be more integrated with setup.py


Let me know how it goes.

**Comment by andrew-harrison** [comment]
Hi Stuart,

Thanks for getting back to me. I did run that script. As far as I can see it was successful (after I installed python-rsvg).

andrew@andrew:~/shoebot-master/install$ ./install_dependencies.sh
[sudo] password for andrew: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjpeg-dev is already the newest version (8c-2ubuntu8).
python-cairo is already the newest version (1.16.2-1).
python-gobject is already the newest version (3.26.1-2).
python-rsvg is already the newest version (2.32.0+dfsg-3).
0 to upgrade, 0 to newly install, 0 to remove and 21 not to upgrade.

Andrew

**Comment by stuaxo** [comment]
Great, if things are working I'll close this ?

**Comment by andrew-harrison** [comment]
Hi Stuart,

That initial post was after I had run the script.

**Comment by stuaxo** [comment]
Doh, yes - I scan read this.    Looks like it wants cairocffi, what happens if you install it using pip ?

**Comment by stuaxo** [comment]
Looks like you don't have a compiler - I should really add this to the install-dependencies file, try

```sudo apt-get install build-essential```

**Comment by stuaxo** [comment]
Hi @andrew-harrison which distro are you using ?    I can install a VM and try and reproduce this.

**Comment by andrew-harrison** [comment]
Hi Stuart, I installed cairocffi and the shoebot install finished successfully, thankyou! 

I've managed to run the balls example and to generate the .png directly rendering to the output file.

I came across an issue when trying to run from the terminal normally, the shoebot window opens but nothing shows:
andrew@andrew:~/shoebot-master$ sbot examples/grid/balls.bot
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

Also from the documentation I wasn't sure where to find the code editor "shoebot", is the install supposed to put this in the launcher?

**Comment by stuaxo** [comment]
Great !  Apologies for not having much time to look into this, I have a toddler monopolising a lot of my ex-spare time.

`shoebot` should be available from the commandline if `sbot` is.
I don't think a launcher is installed automatically, there probably should be a way of doing this.

**Comment by andrew-harrison** [comment]
Don't worry you have been super helpful!

I can't work out how to run `shoebot` , is there a particular file in the directory I'm looking to run?

Any idea what I can do to fix this error:
` TypeError: Couldn't find foreign struct converter for 'cairo.Context' ` ?

**Comment by andrew-harrison** [comment]
Python 2.7.15rc1
Ubuntu 18.04.2 LTS

**Comment by stuaxo** [comment]
Cheers - this is useful info.

This error is a pain, I'll try and reproduce it in a vm in the next few days

So far I've only worked out that it seems to happen when you install cairocffi / cairo in some particular order, I've seen it a lot over the last few years, but never quite worked out what triggers it. 

It seemed to go away once I'd reinstalled pycairo and/or cairocffi.

You might have better luck creating a virtualenv and installing shoebot into it.

**Comment by stuaxo** [comment]
Hi @andrew-harrison 

Thanks for the patience.  install-dependencies.sh has got a little out of date.

I was able to reproduce the bugs you hit.   

Try installing python-gi-cairo and see if it helps:

`$ sudo apt-get install python-gi-cairo`


It seems like cairocffi is dropping python 2.7 support, so I'm updating setup.py to install an older version.

**Comment by stuaxo** [comment]
Try the updated version of install-dependencies.sh again.

Then try

```python setup.py install --user```

You might need to run

```hash -r```

For `sbot` and `shoebot` to show up.

**Comment by andrew-harrison** [comment]
Hi Stuart,

gi-cairo seemed to fix the problem. I can now run all the examples with sbot :smile: 

I still have problem opening Shoebot :disappointed:  Does this mean anything to you?

`andrew@andrew:~$ hash -r`

`andrew@andrew:~$ shoebot`
Traceback (most recent call last):
  File "/usr/local/bin/shoebot", line 11, in <module>
    load_entry_point('shoebot==1.2.2', 'gui_scripts', 'shoebot')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 489, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2793, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2411, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2417, in resolve
ImportError: No module named ide.ide

Thanks again!

**Comment by stuaxo** [comment]
I can definitely look into it.

I had a quick check on locally from the master branch and I can run `shoebot` and the IDE comes up.

The setup.py install --user will have tried to install to your home directory, it mentioning /usr/local which looks like you installed using sudo at some point.

Either one is fine, but it may be getting confused between them.
Since you've got the dependencies all installed, one option would be to remove both, then choose one way to install (sudo or --user).

**Comment by stuaxo** [comment]
I'd try using `setup.py uninstall` + `sudo python setup.py uninstall`, updating and reinstalling.

**Comment by andrew-harrison** [comment]
Hi Stuart,

I'm still having difficulty, when you say uninstall in your last post I assume you mean `pip uninstall` as I didn't think there was a `python uninstall` command.

pip seems to install and uninstall shoebot fine, is the `pip install` installing exactly the same as the local `install` ?

I've also tried virtual environments but same issue.



(Virtuat_Environment) andrew@andrew:~/shoebot-master/shoebot-master/Virtuat_Environment/bin$ shoebot
Traceback (most recent call last):
  File "/home/andrew/.local/bin/shoebot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/andrew/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/andrew/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/andrew/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/andrew/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/andrew/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/andrew/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'shoebot==1.2.2' distribution was not found and is required by the application

**Comment by stuaxo** [comment]
You can do a sort of brute-force uninstall by manually deleting a bunch of files, I actually do this semi-often myself so its not as scary as it sounds.

Go to the site-packages directory, e.g `/home/andrew/.local/lib/python2.7/site-packages/` and delete any shoebot files.

- something like `rm shoebot* -fR`

Then delete the sbot and shoebot binaries in ~.local/bin

If you installed with sudo and want to remove that one go through the same process with the system Shoebot site packages and binaries.

**Comment by stuaxo** [comment]
Sorry, yes I did mean `pip uninstall`

**Comment by stuaxo** [comment]
Hi @andrew-harrison there is a new release on pypi you may wish to try.

There are lots of improvements to docs at docs.shoebot.net

I would have a go at removing any old versions you do before hand, and make sure for any installation you are using python3.x not python2.7 and then you should be good to go.
