### ISSUE TITLE
Text does not accept font, fontsize, weight.

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#278]
Not sure what any of the old test bots are meant to do exactly, but they shouldn't be causing a crash.

Assuming this isn't something tricky this should be release blocker #266 

```
sbot -w test_clip_3.bot       stu@computer  3208  01:43:59 
Gtk-Message: 01:44:08.378: Failed to load module "unity-gtk-module"
Error in the Shoebot script at line 78  in __init__
    ColorMixin.__init__(self  **kwargs):
74: 
75:     def __init__(self, bot, text, x=0, y=0, width=None, height=None, outline=False, ctx=None, enableRendering=True, **kwargs):
76:         self._canvas = canvas = bot._canvas
77:         Grob.__init__(self, bot)
78:         ColorMixin.__init__(self, **kwargs)
    ^ TypeError: __init__() got an unexpected keyword argument 'font'

Traceback (most recent call last):
  File "<string>", line 20, in draw
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/grammar/nodebox.py", line 632, in text
    txt = self.Text(txt, x, y, width, height, outline=outline, ctx=None, **kwargs)
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/grammar/bot.py", line 256, in Text
    return self._makeColorableInstance(Text, args, kwargs)
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/grammar/bot.py", line 228, in _makeColorableInstance
    inst = clazz(self, *args, **kwargs)
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/data/typography.py", line 78, in __init__
    ColorMixin.__init__(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'font'
```

**Comment by stuaxo** [comment]
This bug seems to be about `text` no longer accepting kwargs:

`font="Arial", fontsize=64, weight="bold"`

**Comment by stuaxo** [comment]
WIP branch is up.

Text() needs to not accept **kwargs if at all possible.
A test is needed to ensure it can accept font, size and weight.
Possibly `weight` needs implementing.

**Comment by stuaxo** [comment]
Branch   `bugfix/text-does-not-accept-font-params`
