### ISSUE TITLE
Tracebacks broken

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#285]
The new traceback changes broke something:

Running shoebot/examples/libraries/beziereditor/edit_path.bot

```
$ bot -w edit_path.bot
Gtk-Message: 02:07:45.650: Failed to load module "unity-gtk-module"
Exception in shoebot code
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/grammar/grammar.py", line 256, in run
    self._run_frame(executor, limit=frame_limiter, iteration=iteration)
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/grammar/grammar.py", line 157, in _run_frame
    executor.ns["draw"]()
  File "<string>", line 19, in draw
  File "/home/stu/projects/mine/shoebot-projects/shoebot/lib/beziereditor/__init__.py", line 719, in draw
    elif self.overlap(x, y, pt.x, pt.y) \
  File "/home/stu/projects/mine/shoebot-projects/shoebot/lib/beziereditor/__init__.py", line 183, in overlap
    if abs(x2-x1) < r and abs(y2-y1) < r:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/__init__.py", line 207, in run
    sbot.run(*self.run_args, **self.run_kwargs)
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/grammar/grammar.py", line 309, in run
    errmsg = simple_traceback(e, executor.known_good or "")
  File "/home/stu/projects/mine/shoebot-projects/shoebot/shoebot/grammar/format_traceback.py", line 32, in simple_traceback
    err_where = exc[i + 1].split(',')[1].strip()  # 'line 37 in blah"
IndexError: list index out of range
```

**Comment by stuaxo** [comment]
Fixed in PR.
