### ISSUE TITLE
Images in commands.html do not show on readthedocs.io

### ISSUE THREAD

**Issue by speters33w** [shoebot/shoebot#320]
Images in commands.html do not show on readthedocs.io

They work fine on a local build, on readthedocs the images show as text that says: "test."

![commands_html_readthedocs](https://user-images.githubusercontent.com/25144507/107516691-c5952480-6b7a-11eb-8e6b-2591b9656c1f.png)

**Comment by speters33w** [comment]
It looks like these guys figured it out,

https://github.com/bedops/bedops/issues/224

What they did, I don't know...

https://github.com/bedops/bedops/issues/224

They opened this, which kind of closed without explanation.

https://github.com/readthedocs/readthedocs.org/issues/5709

**Comment by stuaxo** [comment]
It looks like there a few things to get working with RTD, it was trying to build with python2, I re-saved the settings which helped got it onto Python 3.

There a bunch of messages like this the one below in the logs..   on it's assumed we can't use Pango, so shoebot defaults to "FakePango" - a mock, which doesn't do much, except break here :)  [1]

FakePango is a workaround (at the time on RTD Pango either wasn't available or was too old) - so we should probably check if it's possible to just use Pango there (I'm sure it's new enough, it's years later now).

If we can't use Pango then we can fill in the blanks in FakePango - though it means we won't have any examples with text output.

```
[rtd-command-info] start-time: 2021-02-10T14:00:35.292027Z, end-time: 2021-02-10T14:00:47.505800Z, duration: 12, exit-code: 0
/home/docs/checkouts/readthedocs.org/user_builds/shoebot/envs/latest/bin/python -m sphinx -T -b epub -d _build/doctrees -D language=en . _build/epub
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [epub]: targets for 14 source files that are out of date
updating environment: [] 0 added, 2 changed, 0 removed
reading sources... [ 50%] commands
Pango not found - typography will not be available.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot/envs/latest/lib/python3.7/site-packages/shoebot-1.3.1-py3.7.egg/shoebot/__init__.py", line 240, in run
    sbot = create_bot(*self.create_args, **self.create_kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot/envs/latest/lib/python3.7/site-packages/shoebot-1.3.1-py3.7.egg/shoebot/__init__.py", line 194, in create_bot
    from shoebot.grammar import NodeBot
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot/envs/latest/lib/python3.7/site-packages/shoebot-1.3.1-py3.7.egg/shoebot/grammar/__init__.py", line 3, in <module>
    from . import drawbot
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot/envs/latest/lib/python3.7/site-packages/shoebot-1.3.1-py3.7.egg/shoebot/grammar/drawbot.py", line 2, in <module>
    from .bot import Bot
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot/envs/latest/lib/python3.7/site-packages/shoebot-1.3.1-py3.7.egg/shoebot/grammar/bot.py", line 40, in <module>
    from shoebot.data import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot/envs/latest/lib/python3.7/site-packages/shoebot-1.3.1-py3.7.egg/shoebot/data/__init__.py", line 82, in <module>
    from .typography import Text
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot/envs/latest/lib/python3.7/site-packages/shoebot-1.3.1-py3.7.egg/shoebot/data/typography.py", line 104, in <module>
    "ultralight": Pango.Weight.ULTRALIGHT,
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot/envs/latest/lib/python3.7/site-packages/shoebot-1.3.1-py3.7.egg/shoebot/data/typography.py", line 48, in __getattr__
    raise NotImplementedError("FakePango does not implement %s" % item)
NotImplementedError: FakePango does not implement Weight

```

**Comment by rlafuente** [comment]
working images can be seen at [docs.shoebot.net](https://docs.shoebot.net), we're working on #336 to address this

**Comment by rlafuente** [comment]
#336 is done and so is this ticket
