### ISSUE TITLE
I have errors running on windows 10 

### ISSUE THREAD

**Issue by StuckOnEarth** [shoebot/shoebot#423]
I am not familiar with msys2, but I followed the Windows instructions carefully, twice.  

This happens after running: shoebot
sbot does the same thing.

Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\shoebot-script.pyw", line 33, in <module>
    sys.exit(load_entry_point('shoebot==1.4.0b0', 'gui_scripts', 'shoebot')())
  File "C:\msys64\mingw64\bin\shoebot-script.pyw", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:/msys64/mingw64/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:/msys64/mingw64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 887, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:/msys64/home/steve/shoebot/shoebot/__init__.py", line 37, in <module>
    from shoebot.grammar import NodeBot
  File "C:/msys64/home/steve/shoebot/shoebot/grammar/__init__.py", line 3, in <module>
    from . import nodebox
  File "C:/msys64/home/steve/shoebot/shoebot/grammar/nodebox.py", line 8, in <module>
    from .bot import Bot
  File "C:/msys64/home/steve/shoebot/shoebot/grammar/bot.py", line 60, in <module>
    from .grammar import Grammar
  File "C:/msys64/home/steve/shoebot/shoebot/grammar/grammar.py", line 12, in <module>
    from shoebot.core.events import (
  File "C:/msys64/home/steve/shoebot/shoebot/core/events.py", line 24, in <module>
    Event = namedtuple = namedtuple_with_defaults("Event", "type data", dict(data=None))
  File "C:/msys64/home/steve/shoebot/shoebot/core/events.py", line 16, in namedtuple_with_defaults
    if isinstance(default_values, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'

**Comment by stuaxo** [comment]
Hi,
   It looks like python 3.10 deprecated collections.Mapping and it moved to collections.abc.Mapping.
Can you test the fix I pushed to master?

Cheers
S

**Comment by stuaxo** [comment]
I'm going to assume this worked.

The next release will have the fix.
